function(gmsh)
  if(ENABLE_GMSH)
      include_directories(${GMSH_INCLUDE_DIR})
      target_link_libraries(${PROJECT_NAME} gmsh)
  endif()
endfunction()

#function(gmsh)
#  if(ENABLE_GMSH)
#    set(GMSH_HOME "${CMAKE_BINARY_DIR}/RVE_mesher/gmsh")
#    add_dependencies(${PROJECT_NAME} gmsh)
#    include_directories(${GMSH_INCLUDE_DIR})
#    set_property(GLOBAL PROPERTY FIND_LIBRARY_USE_LIB64_PATHS ON)
#    include(GNUInstallDirs)
#    if (APPLE)
#      set(GMSH_LIBRARY ${GMSH_HOME}/${CMAKE_INSTALL_LIBDIR}/libgmsh.dylib)
#    else()
#      set(GMSH_LIBRARY ${GMSH_HOME}/${CMAKE_INSTALL_LIBDIR}/libgmsh.so)
#    endif()
#    target_link_libraries(${PROJECT_NAME} ${GMSH_LIBRARY})
#  endif()
#endfunction()